# Generated by Django 5.1.4 on 2026-06-18 14:40

import apps.seo.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_seo_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="Freeform, e.g. “From $499” or “€90/hour”.",
                        max_length=100,
                        verbose_name="price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="published at"),
                ),
                ("canonical_url", models.URLField(blank=True, verbose_name="canonical URL")),
                (
                    "noindex",
                    models.BooleanField(default=False, verbose_name="hide from search engines"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/", verbose_name="share image"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
            bases=(
                apps.seo.models.SeoFieldsMixin,
                parler.models.TranslatableModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ServiceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One or two plain sentences answering “what is this service?”.",
                        max_length=300,
                        verbose_name="summary",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "area_served",
                    models.CharField(
                        blank=True,
                        help_text="e.g. “United States” or “Berlin and surrounding areas”.",
                        max_length=200,
                        verbose_name="area served",
                    ),
                ),
                (
                    "faq",
                    models.TextField(
                        blank=True,
                        help_text="Q&A blocks. One per pair:\nQ: question\nA: answer",
                        verbose_name="FAQ",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=70, verbose_name="meta title"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=200, verbose_name="meta description"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service Translation",
                "db_table": "content_service_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="content_service_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
