# Generated by Django 5.1.4 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "app_label",
                    models.CharField(max_length=100, unique=True, verbose_name="app label"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
            ],
            options={
                "verbose_name": "plugin",
                "verbose_name_plural": "plugins",
                "ordering": ["app_label"],
            },
        ),
    ]
